//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public string CommentContent { get; set; }
        public int MemberId { get; set; }
        public int NewsId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual News News { get; set; }
    }
}
